apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    run: hello-docker
  name: hello-docker
  namespace: foo
spec:
  containers:
  - image: nginx
    name: hello-docker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
